#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("FoodbitesAPP.Resource", IsApplication=true)]

namespace FoodbitesAPP
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int box_size = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int CustomBorder = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int CustomBorderBt = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int fork = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int iconAval = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int iconHist = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int iconMicro = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int iconPerfil = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int icons8customer48 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int icons8Filter48 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int icons8MapMarker48 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int icons8Marker48 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int icons8Microphone48 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int icons8Past48 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int icons8Share48 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int icons8Star48 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int icons8ThumbUp48 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int iconTend = 2130837520;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000b
			public const int buttonLogin = 2131165195;
			
			// aapt resource value: 0x7f070008
			public const int buttonLoginOK = 2131165192;
			
			// aapt resource value: 0x7f070012
			public const int buttonPerfilAlterar = 2131165202;
			
			// aapt resource value: 0x7f070022
			public const int buttonPesAval = 2131165218;
			
			// aapt resource value: 0x7f070020
			public const int buttonPesHist = 2131165216;
			
			// aapt resource value: 0x7f07001f
			public const int buttonPesMicro = 2131165215;
			
			// aapt resource value: 0x7f070021
			public const int buttonPesPerf = 2131165217;
			
			// aapt resource value: 0x7f070023
			public const int buttonPesTend = 2131165219;
			
			// aapt resource value: 0x7f07002d
			public const int buttonPetDirecao = 2131165229;
			
			// aapt resource value: 0x7f07002c
			public const int buttonPetPartilhar = 2131165228;
			
			// aapt resource value: 0x7f07000a
			public const int buttonRegistar = 2131165194;
			
			// aapt resource value: 0x7f070038
			public const int buttonRegistarOK = 2131165240;
			
			// aapt resource value: 0x7f07000c
			public const int buttonSair = 2131165196;
			
			// aapt resource value: 0x7f070007
			public const int editTextLoginPass = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int editTextLoginUser = 2131165190;
			
			// aapt resource value: 0x7f07001e
			public const int editTextPrecoMax = 2131165214;
			
			// aapt resource value: 0x7f07001c
			public const int editTextPrecoMin = 2131165212;
			
			// aapt resource value: 0x7f070037
			public const int editTextRegEmail = 2131165239;
			
			// aapt resource value: 0x7f070034
			public const int editTextRegNome = 2131165236;
			
			// aapt resource value: 0x7f070036
			public const int editTextRegPass = 2131165238;
			
			// aapt resource value: 0x7f070035
			public const int editTextRegUser = 2131165237;
			
			// aapt resource value: 0x7f070015
			public const int imageButtonFilter = 2131165205;
			
			// aapt resource value: 0x7f070004
			public const int imageViewAvalImg = 2131165188;
			
			// aapt resource value: 0x7f070032
			public const int imageViewPL = 2131165234;
			
			// aapt resource value: 0x7f070028
			public const int imageViewPet = 2131165224;
			
			// aapt resource value: 0x7f07002e
			public const int linearLayout1 = 2131165230;
			
			// aapt resource value: 0x7f070014
			public const int linearLayout99 = 2131165204;
			
			// aapt resource value: 0x7f070000
			public const int linearLayoutAvalLinha = 2131165184;
			
			// aapt resource value: 0x7f070017
			public const int linearLayoutFiltro1 = 2131165207;
			
			// aapt resource value: 0x7f07001a
			public const int linearLayoutFiltro2 = 2131165210;
			
			// aapt resource value: 0x7f070005
			public const int listViewAvaliacoes = 2131165189;
			
			// aapt resource value: 0x7f070033
			public const int listViewPetiscos = 2131165235;
			
			// aapt resource value: 0x7f070003
			public const int ratingBarAval = 2131165187;
			
			// aapt resource value: 0x7f070027
			public const int ratingBarPet = 2131165223;
			
			// aapt resource value: 0x7f070016
			public const int searchViewPes = 2131165206;
			
			// aapt resource value: 0x7f070018
			public const int seekBar1 = 2131165208;
			
			// aapt resource value: 0x7f07000d
			public const int textView1 = 2131165197;
			
			// aapt resource value: 0x7f070002
			public const int textViewAvalDate = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int textViewAvalNome = 2131165185;
			
			// aapt resource value: 0x7f07002b
			public const int textViewCriticas = 2131165227;
			
			// aapt resource value: 0x7f070030
			public const int textViewPLEsta = 2131165232;
			
			// aapt resource value: 0x7f07002f
			public const int textViewPLNome = 2131165231;
			
			// aapt resource value: 0x7f070031
			public const int textViewPLPreco = 2131165233;
			
			// aapt resource value: 0x7f070011
			public const int textViewPerfilEmail = 2131165201;
			
			// aapt resource value: 0x7f07000e
			public const int textViewPerfilNome = 2131165198;
			
			// aapt resource value: 0x7f070010
			public const int textViewPerfilPass = 2131165200;
			
			// aapt resource value: 0x7f07000f
			public const int textViewPerfilUsername = 2131165199;
			
			// aapt resource value: 0x7f070019
			public const int textViewPesKMs = 2131165209;
			
			// aapt resource value: 0x7f07001d
			public const int textViewPesPreMAX = 2131165213;
			
			// aapt resource value: 0x7f07001b
			public const int textViewPesPreMIN = 2131165211;
			
			// aapt resource value: 0x7f070013
			public const int textViewPesTitle = 2131165203;
			
			// aapt resource value: 0x7f07002a
			public const int textViewPetCars = 2131165226;
			
			// aapt resource value: 0x7f070025
			public const int textViewPetEstab = 2131165221;
			
			// aapt resource value: 0x7f070024
			public const int textViewPetNome = 2131165220;
			
			// aapt resource value: 0x7f070029
			public const int textViewPetPreco = 2131165225;
			
			// aapt resource value: 0x7f070026
			public const int textViewPetTlm = 2131165222;
			
			// aapt resource value: 0x7f070009
			public const int textViewTitle = 2131165193;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int AvaliacaoLinha = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Avaliacoes = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Login = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Main = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Perfil = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int Pesquisa = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int Petisco = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int PetiscoLinha = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int PetiscosLista = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int Registar = 2130968585;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int messageSpeakNow = 2131099650;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
